# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arbeitskraft',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('ausweisnummer', models.CharField(blank=True, db_column='Ausweisnummer', max_length=10, null=True)),
                ('nachname', models.CharField(db_column='Nachname', max_length=50)),
                ('vorname', models.CharField(db_column='Vorname', max_length=50)),
                ('strasse', models.CharField(blank=True, db_column='Strasse', max_length=50, null=True)),
                ('hausnummer', models.CharField(blank=True, db_column='Hausnummer', max_length=5, null=True)),
                ('plz', models.IntegerField(blank=True, db_column='PLZ', null=True)),
                ('foto', models.TextField(blank=True, db_column='Foto', null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=30, null=True)),
                ('mobil', models.CharField(blank=True, db_column='Mobil', max_length=30, null=True)),
            ],
            options={
                'db_table': 'arbeitskraft',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArbeitskraftHasProjekt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'arbeitskraft_has_projekt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('zuletzt_gesehen', models.DateTimeField(blank=True, null=True)),
                ('letzter_boot', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beacon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Benutzer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nachname', models.CharField(db_column='Nachname', max_length=50)),
                ('vorname', models.CharField(blank=True, db_column='Vorname', max_length=50, null=True)),
                ('e_mail', models.CharField(db_column='E-Mail', max_length=100)),
                ('hashed_password', models.CharField(db_column='Hashed_Password', max_length=64)),
            ],
            options={
                'db_table': 'benutzer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('strasse', models.CharField(blank=True, db_column='Strasse', max_length=50, null=True)),
                ('hausnummer', models.CharField(blank=True, db_column='Hausnummer', max_length=5, null=True)),
                ('plz', models.IntegerField(blank=True, db_column='PLZ', null=True)),
                ('telefon', models.CharField(blank=True, db_column='Telefon', max_length=30, null=True)),
            ],
            options={
                'db_table': 'firma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Projekt',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=50)),
            ],
            options={
                'db_table': 'projekt',
                'managed': False,
            },
        ),
    ]
